[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#1F618D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6F7"
textColor = "#2C3E50"
font = "sans serif"
